# Streamlit Configuration for Vietnamese Legal AI Chatbot
# Cấu hình Streamlit cho Chatbot AI Pháp lý Việt Nam

[global]
developmentMode = false
logLevel = "info"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
